name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Choisissez la version Python appropriée

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive project files
      run: |
        zip -r my-streamlit-app.zip .

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pa5a3-cccpczcec9gabfc3.northeurope-01'  # Remplacez par le nom de votre Web App Azure
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}  # Le secret que vous avez ajouté
        package: my-streamlit-app.zip
